### ISSUE TITLE
Can I take over code4covid

### ISSUE THREAD

**Issue by codersuntited** [aboutDavid/blog.aboutdavid.me#1]
@aboutDavid if you quit the idea plz let me take over at least
@aboutDavid also I am sorry for posting here, I dont know where else to tell you

**Comment by codersuntited** [comment]
@aboutDavid plz

**Comment by codersuntited** [comment]
@aboutDavid

**Comment by codersuntited** [comment]
@aboutDavid plz!!!!!!!!!!

**Comment by codersuntited** [comment]
@aboutDavid and didn't you buy the domain!!!!!!!!!!!

**Comment by aboutDavid** [comment]
> @aboutDavid and didn't you buy the domain!!!!!!!!!!!

Will you stop please?

**Comment by codersuntited** [comment]
Sorry @aboutDavid 

But can I still take over code4covid

**Comment by codersuntited** [comment]
Really looking towards making code4covid a thing 😞

**Comment by codersuntited** [comment]
I should actually make my own

**Comment by codersuntited** [comment]
And sicne your not using code4covid I can. Use that
